### ISSUE TITLE
Unable to run native after adding custom config converters

### ISSUE THREAD

**Issue by MrSchyzo** [MrSchyzo/tts-rest-wrapper#1]
After [adding custom config converters](https://github.com/MrSchyzo/tts-rest-wrapper/commit/1363cbeb37caa95a739500d67bbbe38edafb5ee0), native Quarkus fails to start.
It looks like the compiled version of the Converter does not have an initializer in its code (see [SmallRye Config](https://smallrye.io/docs/smallrye-config/mapping/mapping.html#_converter_config_mapping)).
Maybe Quarkus does not support converters?

I can always use:
- a workaround that maps a "raw" (Long + String) config interface into a "corrected" data class (Path + PosLong) that can be initialized by a `@Producer` method and `@Inject`ed into the `StorageLazyCache`.
- Java for these conversions (yuck!)

```
2021-10-09 01:02:10,082 ERROR [io.qua.run.Application] (main) Failed to start application (with profile prod): java.lang.NoSuchMethodError: it.mrschyzo.configuration.PositiveLongCoercionConverter.<init>()
        at io.smallrye.config.ConfigMappingContext.lambda$getConverterInstance$7(ConfigMappingContext.java:185)
        at java.util.Map.computeIfAbsent(Map.java:1003)
        at io.smallrye.config.ConfigMappingContext.getConverterInstance(ConfigMappingContext.java:169)
        at io.smallrye.config.ConfigMappingContext.getConverter(ConfigMappingContext.java:104)
        at io.smallrye.config.ConfigMappingContext.lambda$getValueConverter$4(ConfigMappingContext.java:92)
        at java.util.HashMap.computeIfAbsent(HashMap.java:1133)
        at io.smallrye.config.ConfigMappingContext.getValueConverter(ConfigMappingContext.java:89)
        at it.mrschyzo.configuration.StorageConfiguration1648742051Impl.<init>(Unknown Source)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:490)
        at io.smallrye.config.ConfigMappingLoader.configMappingObject(ConfigMappingLoader.java:59)
        at io.smallrye.config.ConfigMappingContext.constructGroup(ConfigMappingContext.java:80)
        at io.smallrye.config.ConfigMappingContext.constructRoot(ConfigMappingContext.java:76)
        at io.smallrye.config.ConfigMappingProvider.mapConfiguration(ConfigMappingProvider.java:811)
        at io.smallrye.config.ConfigMappingProvider.mapConfiguration(ConfigMappingProvider.java:794)
        at io.smallrye.config.ConfigMappings.mapConfiguration(ConfigMappings.java:54)
        at io.smallrye.config.ConfigMappings.registerConfigMappings(ConfigMappings.java:36)
        at io.quarkus.arc.runtime.ConfigRecorder.registerConfigMappings(ConfigRecorder.java:81)
        at io.quarkus.deployment.steps.ConfigBuildStep$registerConfigClasses-2116437784.deploy_0(ConfigBuildStep$registerConfigClasses-2116437784.zig:132)
        at io.quarkus.deployment.steps.ConfigBuildStep$registerConfigClasses-2116437784.deploy(ConfigBuildStep$registerConfigClasses-2116437784.zig:40)
        at io.quarkus.runner.ApplicationImpl.doStart(ApplicationImpl.zig:579)
        at io.quarkus.runtime.Application.start(Application.java:101)
        at io.quarkus.runtime.ApplicationLifecycleManager.run(ApplicationLifecycleManager.java:101)
        at io.quarkus.runtime.Quarkus.run(Quarkus.java:66)
        at io.quarkus.runtime.Quarkus.run(Quarkus.java:42)
        at io.quarkus.runtime.Quarkus.run(Quarkus.java:119)
        at io.quarkus.runner.GeneratedMain.main(GeneratedMain.zig:29)
```

**Comment by MrSchyzo** [comment]
"Solved" with [this commit](https://github.com/MrSchyzo/tts-rest-wrapper/commit/4115046bb44279fe07f8e2c5f28a9b222b068c6d)
